version: 2
jobs:
  terraform-review:
    working_directory: ~/build

    docker:
      - image: hashicorp/terraform:latest

    steps:
      - checkout
      - run:
          name: terraform init
          command: terraform init
          working_directory: ~/build/deploy/terraform/eu-west-1

      - run:
          name: terraform plan
          command: sh ./terraform-plan.sh
          working_directory: ~/build/deploy/scripts

      - persist_to_workspace:
          root: /root/build
          paths:
            - ./

  terraform-apply:
    working_directory: /home/circleci/terraform/deploy/scripts

    docker:
      - image: hashicorp/terraform:latest

    steps:
      - attach_workspace:
          at: /home/circleci/terraform
      - run:
          name: apply terraform
          command: sh ./terraform-apply.sh

  build:
    working_directory: ~/code/
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: update-npm
          command: sudo npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: build the code
          command: npm run build
      - persist_to_workspace:
          root: /home/circleci/code
          paths:
            - ./

  test:
    working_directory: ~/code/
    docker:
      - image: circleci/node:10.12.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: sudo npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run the tests
          command: npm run tests

  deploy-site:
    working_directory: ~/code/
    docker:
      - image: circleci/python:jessie-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: update-npm
          command: sudo npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: deploy
          command: sh ./deploy/scripts/deploy.sh ${CIRCLE_SHA1}

      - persist_to_workspace:
          root: /home/circleci/code
          paths:
            - ./

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test
      - hold-code:
          type: approval
          requires:
            - build
            - test
      - terraform-review:
          requires:
            - hold-code
      - hold-terraform:
          type: approval
          requires:
            - terraform-review
      - terraform-apply:
          requires:
            - hold-terraform
      - deploy-site:
          requires:
            - terraform-apply